version: "3.0"
services:
  jenkins:
    build: .
    restart: always
    environment:
      - TZ=Asia/Singapore
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home:
    external: true
